name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm ci

      - name: Build page
        run: npm run build

      - name: Save artifact
        uses: actions/upload-artifact@v1
        with:
          name: build-folder
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: build-folder

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
